server:
  port: 8000

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/user-service/**
          filters:
            - StripPrefix=2
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/product-service/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/order-service/**
          filters:
            - StripPrefix=2