import type { Metadata } from 'next'
import '@/styles/global.css'

import Providers from '@/app/providers'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bookstore App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body
      className={cn(
        'bg-neutral-200 dark:bg-background antialiased',
        inter.className,
      )}
    >
    <Providers>
      <Toaster richColors />
      {children}
    </Providers>
    </body>
    </html>
  )
}
