server:
  port: 8080
  servlet:
    context-path: /user-service

app:
  url: http://localhost:8080/user-service

spring:
  application:
    name: user-service
  profiles:
    active: @spring.profiles.active@