server:
  port: 8080
  servlet:
    context-path: /user-service

app:
  api-gateway-url: http://localhost:8000/api/user-service

spring:
  application:
    name: user-service
  profiles:
    active: @spring.profiles.active@