spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_DATABASE:localhost}:3306/bookstore?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_ROOT_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 60000
jwt:
  signerKey: ${JWT_SIGNER_KEY:uGn1btxMAz77FBExhcThICMJpEWG4fwLu6pJiwlObSIubo7ivat3KSD54PRN0467}
  valid-duration: ${JWT_VALID_DURATION:3600} # seconds
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:864000} # seconds
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    title: Bookstore API documentation
    version: 1.0.0
    description: API for managing books in a bookstore
    server: http://localhost:${server.port}${server.servlet.context-path}
    api-docs: bookstore-api