server:
  port: 8082
  servlet:
    context-path: /order-service

app:
  api-gateway-url: http://localhost:8000/api/order-service
  product-service-url: http://localhost:8081/product-service

spring:
  application:
    name: order-service
  profiles:
    active: @spring.profiles.active@