server:
  port: 8081
  servlet:
    context-path: /product-service

app:
  url: http://localhost:8081/product-service

spring:
  application:
    name: product-service
  profiles:
    active: @spring.profiles.active@