server:
  port: 8081
  servlet:
    context-path: /product-service

app:
  api-gateway-url: http://localhost:8000/product-service

spring:
  application:
    name: product-service
  profiles:
    active: @spring.profiles.active@